name: page
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  get: 4.6.5
  font_awesome_flutter:
  url_launcher:
  simple_icons: ^7.10.0
  google_fonts:
  url_strategy:
  lottie:
  flutter: 
    sdk: flutter
  intl: ^0.18.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  animated_native_splash:
  flutter_test: 
    sdk: flutter

animated_native_splash:
  jsonFile: asset/lottie_2.json

web:
  build:
    generate: true
    options:
      --no-sound-null-safety
    output: build

flutter:
  assets:
    - asset/
  uses-material-design: true

